= Introduction
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

Barcelona City Council has a policy for using and developing free software which is set out in the http://ajuntament.barcelona.cat/digital/ca/documentacio[Government Measure: Free software and agile development of public administration services], approved in October 2017.

This policy includes a series of principles and guidelines that are outlined in the following documents, annexed to the measure:

* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_2_codi_de_practiques_tecnologiques_cat_2017_af.pdf[Code of Technological Practices]
* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_4_guia_sobre_sobirania_tecnologica_cat_2017_af_2.pdf[Guide to Technological Sovereignty]
* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_6_guia_de_compra_publica_tic_cat_af_9en.pdf[Guide to Public ICT Procurement]

This Guide spells out these principles and guidelines in a series of measures and recommendations to help staff of the Municipal Institute of Information Technology (IMI), the ICT body of the Barcelona City Council, in their daily work on projects based on free software.
It covers aspects such as:

* Looking for and designing solutions
* Service procurement
* Developing, implementing and maintaining information systems
* Participation in free software communities

== Benefits of using and developing free IT solutions

The main benefit expected from using and developing free software is that the City Council regains or maintains control of their computing, not ceding it to private hands.
It is crucial for an entity that implements public services and processes a lot of information about citizens to know exactly what it is being executed, in what computers, who has access to the data, etc. As the https://www.gnu.org[GNU project] puts it:

:quote-url: pass:macros[https://www.gnu.org/philosophy/government-free-software.en.html[Measures Governments Can Use to Promote Free Software]]

[quote, Richard Stallman, {quote-url}]
--
The state needs to insist on free software in its own computing for the sake of its computational sovereignty (the state's control over its own computing). All users deserve control over their computing, but the state has a responsibility to the people to maintain control over the computing it does on their behalf. Most government activities now depend on computing, and its control over those activities depends on its control over that computing. Losing this control in an agency whose mission is critical undermines national security.
--

Both the GNU document above and the https://ajuntament.barcelona.cat/digital/en/blog/barcelona-digital-government-open-agile-and-participatory[Release note of the Government Measure: Free software and agile development of public administration services] envision other benefits:

* Encouraging local software support businesses, more easily including small and medium-sized businesses in the procurement process.
* Creating crucial new capabilities in the public sector through internalisation of staff and a programme to create in-house skills to drive transformation.
* Increasing transparency and auditability of administrative processes.
* Never requiring individuals or organizations that need to interact with the City Council to use a nonfree program (that would be equivalent to a state-sanctioned monopoly).
* Ensuring data sovereignty, privacy and security, for the citizens and for the municipality.
* Avoiding vendor lock-in and, more generally, freeing IT policy and planning from commercial strategies, constructing better tailored, more flexible, more sustainable solutions.
* Saving money, by avoiding proprietary license fees and through sharing and pooling of resources among municipalities and other government agencies.

== Purpose of this Guide

This Guide serves a double purpose:

. To help IMI staff use technologies based on free software so they make the most of its advantages and minimise potential risks.

. To help maintain Barcelona City Council's reputation as a transparent and reliable
institutional collaborator in free software projects, taking into account the sector's best practices.

Despite the enormous diversity that currently exists among free software projects, a series of practices have gradually arisen that are shared by most projects and organisations which have a certain degree of success.
These cover technical and legal aspects, as well as project management.
Some of these practices can be considered necessary, in the sense that the operational dynamics of free software projects reward certain types of conduct and penalise others.

In some cases free software common practices can be very different from working methods used when there is no intention of publishing the source code under a free license.
This means IMI's learning process and adaptation will have a cost, but we believe that it will be far outweighed by the organisational improvements it will bring – together with the incorporating agile methods –.

This document codifies and adapts these best practices to IMI, so they may serve as a guide in the learning process and in decision-making.

== To find out more

A very good resource for understanding all the technical, legal and social aspects of free software development is Karl Fogel’s book https://producingoss.com/en/index.html[Producing Open Source Software] (the 2017 edition, only available in an e-version, which can be freely consulted online).
The book uses the term _open source_, which basically refers to the same range of projects as _free software_.
(The proponents of both terms differ on their political and philosophical views, but the practical aspects we treat in this document are mostly shareable by both camps.)
We have taken many of the practical recommendations in that book into account in drawing up this Guide.

The Guide also contains lots of recommendations on service procurement.
A good document for understanding the particular features of public procurement of free software in the context of the European Union is https://joinup.ec.europa.eu/document/guideline-public-procurement-open-source-software[Guideline on public procurement of Open Source Software], published in 2010 by Rishab Aiyer Ghosh, Ruediger Glott, Patrice-Emmanuel Schmitz and Abdelkrim Boujraf, and commissioned by the European Commission under the https://joinup.ec.europa.eu//[Join Up] initiative.
