
.DRAFT
****
Indeed. Guide to Open Source Software Project Management.
****

= 1. Introduction

Barcelona City Council has a policy for using and developing free or open source software which is set out in the http://ajuntament.barcelona.cat/digital/ca/documentacio[Government Measure on Open Digitisation: Free software and agile development of public administration services], approved in October 2017

This policy includes a series of principles and guidelines that are outlined in the following documents, annexed to the measure:

* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_2_codi_de_practiques_tecnologiques_cat_2017_af.pdf[Code of Technological Practices]
* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_4_guia_sobre_sobirania_tecnologica_cat_2017_af_2.pdf[Guide to Technological Sovereignty]
* http://ajuntament.barcelona.cat/digital/sites/default/files/guia_adt_6_guia_de_compra_publica_tic_cat_af_9en.pdf[Guide to Public ICT Procurement]

This Guide spells out these principles and guidelines in a series of measures and recommendations to help municipal IT (IMI) staff in their daily work on projects based on open source software. It covers aspects such as:

* Looking for and designing solutions
* Service procurement
* Developing, implementing and maintaining information systems
* Participation in open communities

== 1.1. Purpose of this Guide

This Guide serves a double purpose:

a.  To help IMI staff use technologies based on open source software so they make the most of the advantages and minimise the potential risks.
b.  To help maintain Barcelona City Council’s reputation as a transparent and reliable institutional collaborator in open source software projects that takes the sector’s best practices into account.

The benefits expected from using free software and open standards are explained in the http://ajuntament.barcelona.cat/digital/sites/default/files/le_mesuradegovern_v2.pdf[Government Measure on Open Digitisation] (page 22). We reproduce them here:

* *Transparency*: the source code can be examined and audited by anyone with sufficient technical knowledge, with no need for explicit permission from the manufacturer or the City Council. Without this property it is difficult to trust the neutrality and security of a growing number of governmental and administrative processes that are implemented in the form of software, such as voting processes.
* *Interoperability*: the use of open formats and standards enables different systems, possibly made by different manufacturers, to operate together without any legal or technical barriers. This opens up possibilities of integrating different systems, to reuse data and improve processes, for example. It also ensures that the general public are not forced to use the technological solutions of specific providers to interact with the public authority.
* *Sovereignty*: transparency and interoperability greatly reduce dependence on the commercial strategies of manufacturers. Users, in this case the City Council, are free to decide which systems they want to develop, resize or replace, as well as their own policies on security, privacy, updates and access to the systems. In the case of organisations, sovereignty also encourages control over their own processes and knowledge generation and conservation.
* *Flexibility*: systems can be better adapted to the users’ needs, and they can be adapted and extended as those needs evolve, without depending on a particular provider. Not only is development more flexible, it is much easier and cheaper to assess alternatives as well, while operating conditions and maintenance can be modified more easily too.
* *Sustainability*: interoperability enables system parts that need renewing to be replaced without the need for data to ever be unavailable. Greater sovereignty also means less risk of any part of the system, including the hardware, becoming obsolete. The collaboration (between people and organisations) that is encouraged by free licences can be a great help in making a system more durable and stable.
* *Efficiency*: factors such as cost savings on paying for licences, more competition between suppliers, less risk of obsolescence and the possibility of sharing costs with other bodies or organisations, mean free software based on open standards is the best option for ensuring public authorities are efficient, as they are required to be by law. The huge amount of software that can be combined allows many domains to achieve solutions that are much better adapted to the end requirements with little use of resources.
* *Reliability and security*: being free of commercial strategies means users can demand better quality services and take advantage of all the adjustments and improvements provided by the development and support community of each tool.
* *Innovation*: transparency, and a fortunate combination of collaboration and competition, means open source software is enormously fertile terrain for technological, social and process innovation. The direct beneficiaries of this knowledge production are the people who produce and use the software but the whole of society benefits indirectly.

Besides the commitment to base IMI’s technological architecture on open source software, we need to know and exploit the particular features of the projects and open communities.

Despite the enormous diversity that currently exists among open source projects, a series of practices have gradually arisen that are shared by most projects and organisations which achieve a certain degree of success. That includes technical and legal aspects, as well as project management. We could say that some of these are must-adopt practices, in the sense that the working dynamics of open source projects reward certain types of conduct and penalise others.

These practices are geared towards facilitating the widest possible diversity among the participants, very often without any centralised coordination, while maintaining the quality of the product at the same time. In some cases they might be very different from the way of working when there is no intention of publishing the source code. That means IMI’s learning process and adaptation will have a cost but we believe that it will be far outweighed by the organisational improvements it will bring – together with the incorporation of agile methods – as well as all the benefits mentioned above. As Karl Fogel says in https://producingoss.com/en/introduction.html[Producing Open Source Software]:

__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
“the open source projects your organisation participates in are a membrane through which your managers and developers are regularly exposed to people and ideas outside your organisational hierarchy. It’s like having the benefits of attending a conference but still getting daily work done and without incurring travel expenses. In a successful open source project these benefits, once they start arriving, greatly outweigh the costs”.
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

To sum up, this guide intends to explain the best practices available for using and developing open source software. It does so by codifying and adapting these best practices to IMI, so they may serve as a guide in the learning process and in decision-making.

== 1.2. To find out more

A very good resource for understanding all the technical, legal and social aspects of open source software is Karl Fogel’s book https://producingoss.com/en/index.html[Producing Open Source Software] (the 2017 edition, only available in an e-version, which can be freely consulted online). We have taken many of the recommendations in that book into account in drawing up this Guide

The Guide also contains lots of recommendations on service procurement. A good document for understanding the particular features of public procurement of open source software is https://joinup.ec.europa.eu/document/guideline-public-procurement-open-source-software[Guideline on public procurement of Open Source Software], published in 2010 by Rishab Aiyer Ghosh, Ruediger Glott, Patrice-Emmanuel Schmitz and Abdelkrim Boujraf, and commissioned by the European Commission under the https://joinup.ec.europa.eu//[Join Up] initiative.

= 2. Structure of this Guide

This Guide contains...

== 2.1. Use scenario tags

In this section we define...

=== 2.1.1 `Integration` Scenario

This scenario may involve...

=== 2.1.2 `Adaptation` Scenario

This scenario might involve...

=== 2.1.3 `Plugin` Scenario

This is a scenario...

=== 2.1.4 `NewProduct` Scenario

When there is...

=== 2.1.5 `Publication` Scenario

Barcelona City Council owns...

=== 2.1.6 `Document` Scenario

Sometimes you may...

== 2.2. Tags for stages and times in projects

When classifying measures...

= 3. Open development

In free or open source software...

== 3.1. Work in the open from day one

A really important aspect to bear in mind is...

== 3.2. Procurement for open development

Measure: Award the contract to...

== 3.3. Dissemination of the project

Measure: Chose a good name for...

== 3.4. Parametrisation, configuration and installation

Measure: Get the successful bidders to...

== 3.5. Packaging and rollout

Measure: Get the successful bidder responsible for...

== 3.6. Use open formats and standards

Measure: Check the user interface meets...

== 3.7. Internationalisation

Measure: Define and budget the technical requirements so...

== 3.8. Opening a code that was initially closed

This section will explain how to...

= 4. Technical infrastructure

The technical infrastructure required for...

== 4.1. Websites associated with the project

A typical software project might have...

== 4.2. Code repository and version control

A key element of the project development website is...

== 4.3. Incident management tool

One tool all open code projects need is...

== 4.4. Integration infrastructure and testing

Recommendation: Link the main repository to...

== 4.5. Internal and external communication channels

The first lines of communication between developers are...

= 5. Component management

== 5.1. Look for and select open code components

In all likelihood, unless our need is...

== 5.2. Managing dependencies

Measure: Keep a thorough record of...

== 5.3. Replace the usual private services

Measure: Use Piwik...

= 6. Open communities

There are many levels of...

== 6.1. Contributing to open communities

The concept of contribution covers much more than...

== 6.2. Open community management and governance

Measure: Recognise people who...

== 6.3. Proper use of the communication channels

Measure: Avoid...

= 7. Legal aspects

Open source projects are...

== 7.1. Intellectual property

Until now, contracts with suppliers stipulated that...

== 7.2. Choose a licence for the code

There are three options...

== 7.3. Comply with the licence obligations

Measure: Write a checklist with...

= 8. Documentation

Measure: Upload a ``README`` file to...
